version: "3.8"
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=elearning
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "database-mysql" ]
      interval: 5s
      timeout: 10s
      retries: 10
    expose:
      - "3306"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # restart: unless-stopped
    depends_on:
      database-mysql:
        condition: service_healthy
    environment:
      - DB_HOST=database-mysql
      - DB_PORT=3306
      - DB_NAME=elearning
      - DB_PASSWORD=123456
      - DB_USERNAME=root
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=tnthotel2004@gmail.com
      - SMTP_PASS=meym zdjw zgbr jzic
      - ACCESS_TOKEN_SECRET=b7abed762362d429aa528a1f1b554289ce099e32de62effa60868d58dbe4e5c2c79ccced8c552646f0c031bd2df8d654f297da940c8bd72d0f8089a68513c816
      - REFRESH_TOKEN_SECRET=86c6048e052e4980f3d60e0b8e262301e0cbb5ac6eb44a8fa65b8fa456d95e4242bb455815f6212b4fa320d2357b1694f60b2f3f0830b636f7fbe78315e6a797
      - DB_DIALECT=mysql
      - PORT=9000
      - GOOGLE_CLIENT_ID=947153887279-oohcm8jt3r249qvo6fcunjibp2bh7103.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=http://localhost:9000/api/auth/google/callback
      - SESSION_SECRET=mySuperSecretKey123!
      - HOST_NAME=0.0.0.0
      - NODE_ENV=development
      - CLOUDINARY_CLOUD_NAME=doycdzvf6
      - CLOUDINARY_API_KEY=179171766789256
      - CLOUDINARY_API_SECRET=HFmVtheG18WESIi_5cN-WhDGZyA
    ports:
      - "9000:9000"

volumes:
  db_data:
