version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - HOST_NAME=0.0.0.0
    ports:
      - "9000:9000"