version: '3.8'

services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=elearning
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database-mysql"]
      interval: 5s
      timeout: 10s
      retries: 10
    expose:
      - 3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database-mysql:
        condition: service_healthy
    environment:
      - DB_HOST=database-mysql
      - DB_PORT=3306
    ports:
      - "9000:9000"
